"""
SQLite-backed cache for scraped game data.

Single database file at `data/cache.db` with four tables:

    games               one row per game — odds lists are JSON-encoded
    cached_keys         one row per (sport, cache_key) that has been fetched,
                        including empty days, so we don't re-fetch them forever
    backtest_history    one row per (sport, season_year, model) — aggregate
                        backtest stats persisted by `backtest_history.py`
                        for fast retrieval by /api/history
    picks_log           one row per pick generated by the live prefetch flow.
                        Settled (W/L, units) once the game's scores arrive.
                        Powers the History tab's recent-picks ledger and the
                        rolling cumulative-units chart.

Public API preserves the shape the old parquet store exposed, so all callers
in runner.py, backtest.py, and prefetch.py continue to work:

    save(sport, key, df)
    load(sport, key) -> DataFrame | None
    exists(sport, key) -> bool
    list_available(sport) -> list[str]

`max_cached_date(sport)` is used by the prefetch for incremental gap-fill.

History/log API:

    save_backtest_history(sport, season_year, model, ...)
    load_backtest_history(sport=None, model='logreg') -> list[dict]
    log_picks(sport, cache_key, game_date, picks, model='logreg') -> int
    unsettled_picks(sport=None, max_age_days=30) -> list[dict]
    settle_pick_record(pick_id, away_score, home_score) -> bool
    recent_settled_picks(limit=50) -> list[dict]
    daily_performance(days=30) -> list[dict]
"""

from __future__ import annotations

import datetime
import json
import os
import sqlite3
from typing import Optional

import pandas as pd

import config

_DB_PATH = os.path.join(os.path.dirname(__file__), 'data', 'cache.db')

_SCHEMA = """
CREATE TABLE IF NOT EXISTS games (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  sport        TEXT    NOT NULL,
  cache_key    TEXT    NOT NULL,
  date         TEXT,
  week         INTEGER,
  row_index    INTEGER NOT NULL,
  away_lines   TEXT    NOT NULL,
  home_lines   TEXT    NOT NULL,
  away_score   TEXT,
  home_score   TEXT,
  away_team    TEXT,
  home_team    TEXT,
  away_abbr    TEXT,
  home_abbr    TEXT,
  sportsbooks  TEXT
);

CREATE TABLE IF NOT EXISTS cached_keys (
  sport        TEXT NOT NULL,
  cache_key    TEXT NOT NULL,
  fetched_at   TEXT NOT NULL,
  PRIMARY KEY (sport, cache_key)
);

CREATE INDEX IF NOT EXISTS idx_games_sport_key  ON games(sport, cache_key);
CREATE INDEX IF NOT EXISTS idx_games_sport_date ON games(sport, date);

CREATE TABLE IF NOT EXISTS backtest_history (
  sport          TEXT    NOT NULL,
  season_year    INTEGER NOT NULL,
  model          TEXT    NOT NULL,
  start_date     TEXT    NOT NULL,
  end_date       TEXT    NOT NULL,
  total_games    INTEGER NOT NULL,
  games_picked   INTEGER NOT NULL,
  correct_picks  INTEGER NOT NULL,
  win_rate       REAL,
  flat_units     REAL    NOT NULL,
  kelly_units    REAL    NOT NULL,
  roi_flat       REAL,
  roi_kelly      REAL,
  max_drawdown   REAL,
  game_log_json  TEXT    NOT NULL,
  computed_at    TEXT    NOT NULL,
  PRIMARY KEY (sport, season_year, model)
);

CREATE TABLE IF NOT EXISTS rolling_backtest_cache (
  sport            TEXT    NOT NULL,
  end_date         TEXT    NOT NULL,
  window_days      INTEGER NOT NULL,
  start_date       TEXT    NOT NULL,
  model            TEXT    NOT NULL,
  total_games      INTEGER NOT NULL,
  games_picked     INTEGER NOT NULL,
  correct_picks    INTEGER NOT NULL,
  win_rate         REAL,
  flat_units       REAL    NOT NULL,
  kelly_units      REAL    NOT NULL,
  max_drawdown     REAL    NOT NULL,
  daily_units_json TEXT    NOT NULL,
  game_log_json    TEXT    NOT NULL,
  computed_at      TEXT    NOT NULL,
  PRIMARY KEY (sport, end_date, window_days, model)
);

CREATE INDEX IF NOT EXISTS idx_rolling_window ON rolling_backtest_cache(window_days, end_date DESC);

CREATE TABLE IF NOT EXISTS picks_log (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  sport             TEXT    NOT NULL,
  cache_key         TEXT    NOT NULL,
  game_date         TEXT    NOT NULL,
  game_index        INTEGER NOT NULL,
  away_team         TEXT,
  home_team         TEXT,
  away_abbr         TEXT,
  home_abbr         TEXT,
  pick              TEXT    NOT NULL,
  confidence        REAL,
  away_prob         REAL,
  home_prob         REAL,
  away_lines_json   TEXT,
  home_lines_json   TEXT,
  bet_line          TEXT,
  ev                REAL,
  unit_size         REAL,
  model             TEXT    NOT NULL,
  away_score        INTEGER,
  home_score        INTEGER,
  actual            TEXT,
  result            TEXT,
  flat_units        REAL,
  kelly_units       REAL,
  created_at        TEXT    NOT NULL,
  settled_at        TEXT,
  UNIQUE (sport, cache_key, game_index, model)
);

CREATE INDEX IF NOT EXISTS idx_picks_log_unsettled ON picks_log(actual);
CREATE INDEX IF NOT EXISTS idx_picks_log_sport_date ON picks_log(sport, game_date DESC);
CREATE INDEX IF NOT EXISTS idx_picks_log_settled_at ON picks_log(settled_at DESC);
"""

# Columns added after initial release. SQLite has no IF NOT EXISTS for ALTER,
# so we attempt each one and swallow the OperationalError raised when the
# column is already present. Idempotent across runs.
_MIGRATIONS = [
    "ALTER TABLE games ADD COLUMN away_team TEXT",
    "ALTER TABLE games ADD COLUMN home_team TEXT",
    "ALTER TABLE games ADD COLUMN away_abbr TEXT",
    "ALTER TABLE games ADD COLUMN home_abbr TEXT",
    "ALTER TABLE games ADD COLUMN sportsbooks TEXT",
    "ALTER TABLE backtest_history ADD COLUMN max_drawdown REAL",
]


def _connect() -> sqlite3.Connection:
    """Open the cache DB, creating the schema on first touch."""
    os.makedirs(os.path.dirname(_DB_PATH), exist_ok=True)
    conn = sqlite3.connect(_DB_PATH, timeout=30)
    # WAL lets the prefetch thread write while the API serves reads, so
    # long-running endpoints (e.g. /api/backtest) aren't blocked by ingestion.
    conn.execute('PRAGMA journal_mode=WAL')
    conn.execute('PRAGMA synchronous=NORMAL')
    conn.executescript(_SCHEMA)
    for stmt in _MIGRATIONS:
        try:
            conn.execute(stmt)
        except sqlite3.OperationalError:
            pass
    return conn


def _label_column(sport: str) -> tuple[str, str]:
    """Return (column_name, column_value) for the Date/Week column of a sport."""
    if config.SPORTS[sport]['date_type'] == 'date':
        return 'Date', ''
    return 'Week', ''


def _derive_date_week(sport: str, cache_key: str) -> tuple[Optional[str], Optional[int]]:
    """Split a cache_key into (date, week) columns for the games table."""
    if config.SPORTS[sport]['date_type'] == 'date':
        return cache_key, None
    try:
        return None, int(cache_key)
    except ValueError:
        return None, None


def _coerce_score(value) -> Optional[str]:
    """Normalize a score cell to a TEXT value or NULL."""
    if value is None:
        return None
    if isinstance(value, float) and pd.isna(value):
        return None
    return str(value)


def _coerce_lines(value) -> Optional[list]:
    """Return a list of line strings, or None for missing/NaN cells."""
    if value is None:
        return None
    if isinstance(value, float) and pd.isna(value):
        return None
    try:
        return list(value)
    except TypeError:
        return None


def _coerce_text(value) -> str:
    """Normalize a text cell to a plain str (empty for missing/NaN)."""
    if value is None:
        return ''
    if isinstance(value, float) and pd.isna(value):
        return ''
    return str(value)


def save(sport: str, key: str, df: pd.DataFrame) -> None:
    """Replace any existing rows for (sport, key) with the new DataFrame.

    Rows with NaN/missing Away Lines or Home Lines are skipped — without odds
    there's nothing to predict on, and upstream pd.concat() can pad rows when
    the scores frame is longer than the lines frame.
    """
    cache_key = str(key)
    date_col, week_col = _derive_date_week(sport, cache_key)
    now = datetime.datetime.utcnow().isoformat(timespec='seconds')

    rows = []
    for i, row in df.iterrows():
        away_lines = _coerce_lines(row.get('Away Lines'))
        home_lines = _coerce_lines(row.get('Home Lines'))
        if away_lines is None or home_lines is None:
            continue
        sportsbooks = _coerce_lines(row.get('Sportsbooks')) or []
        rows.append((
            sport,
            cache_key,
            date_col,
            week_col,
            int(i),
            json.dumps(away_lines),
            json.dumps(home_lines),
            _coerce_score(row.get('Away Score')),
            _coerce_score(row.get('Home Score')),
            _coerce_text(row.get('Away Team')),
            _coerce_text(row.get('Home Team')),
            _coerce_text(row.get('Away Abbr')),
            _coerce_text(row.get('Home Abbr')),
            json.dumps(sportsbooks),
        ))

    conn = _connect()
    try:
        with conn:
            conn.execute(
                'DELETE FROM games WHERE sport = ? AND cache_key = ?',
                (sport, cache_key),
            )
            if rows:
                conn.executemany(
                    'INSERT INTO games '
                    '(sport, cache_key, date, week, row_index, '
                    ' away_lines, home_lines, away_score, home_score, '
                    ' away_team, home_team, away_abbr, home_abbr, sportsbooks) '
                    'VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
                    rows,
                )
            conn.execute(
                'INSERT INTO cached_keys (sport, cache_key, fetched_at) '
                'VALUES (?, ?, ?) '
                'ON CONFLICT(sport, cache_key) DO UPDATE SET fetched_at = excluded.fetched_at',
                (sport, cache_key, now),
            )
    finally:
        conn.close()


def load(sport: str, key: str) -> Optional[pd.DataFrame]:
    """Return the cached DataFrame for (sport, key), or None if never fetched."""
    cache_key = str(key)

    conn = _connect()
    try:
        fetched = conn.execute(
            'SELECT 1 FROM cached_keys WHERE sport = ? AND cache_key = ?',
            (sport, cache_key),
        ).fetchone()
        if fetched is None:
            return None

        rows = conn.execute(
            'SELECT away_lines, home_lines, away_score, home_score, '
            '       away_team, home_team, away_abbr, home_abbr, sportsbooks '
            'FROM games WHERE sport = ? AND cache_key = ? '
            'ORDER BY row_index',
            (sport, cache_key),
        ).fetchall()
    finally:
        conn.close()

    date_type = config.SPORTS[sport]['date_type']
    label_col = 'Date' if date_type == 'date' else 'Week'
    label_val = cache_key if date_type == 'date' else f'Week {cache_key}'

    away_lines: list = []
    home_lines: list = []
    away_scores: list = []
    home_scores: list = []
    away_teams: list = []
    home_teams: list = []
    away_abbrs: list = []
    home_abbrs: list = []
    sportsbooks_col: list = []
    for (away_json, home_json, away_score, home_score,
         away_team, home_team, away_abbr, home_abbr, sportsbooks_json) in rows:
        away_lines.append(json.loads(away_json))
        home_lines.append(json.loads(home_json))
        away_scores.append(away_score)
        home_scores.append(home_score)
        away_teams.append(away_team or '')
        home_teams.append(home_team or '')
        away_abbrs.append(away_abbr or '')
        home_abbrs.append(home_abbr or '')
        sportsbooks_col.append(json.loads(sportsbooks_json) if sportsbooks_json else [])

    df = pd.DataFrame({
        label_col: [label_val] * len(rows),
        'Away Lines': away_lines,
        'Home Lines': home_lines,
        'Away Score': away_scores,
        'Home Score': home_scores,
        'Away Team': away_teams,
        'Home Team': home_teams,
        'Away Abbr': away_abbrs,
        'Home Abbr': home_abbrs,
        'Sportsbooks': sportsbooks_col,
    })
    return df


def exists(sport: str, key: str) -> bool:
    """True if (sport, key) has ever been fetched (even if it had zero games)."""
    conn = _connect()
    try:
        row = conn.execute(
            'SELECT 1 FROM cached_keys WHERE sport = ? AND cache_key = ?',
            (sport, str(key)),
        ).fetchone()
    finally:
        conn.close()
    return row is not None


def list_available(sport: str) -> list[str]:
    """Return every cache_key that has been fetched for sport."""
    conn = _connect()
    try:
        rows = conn.execute(
            'SELECT cache_key FROM cached_keys WHERE sport = ?',
            (sport,),
        ).fetchall()
    finally:
        conn.close()
    return [r[0] for r in rows]


def max_cached_date(sport: str) -> Optional[datetime.date]:
    """
    Latest calendar date we have cached for a sport, across both date- and
    week-based sports. Returns None if nothing is cached.

    For week-based sports the returned date is an approximation: Week1-start
    plus 7*(week-1) days. That's close enough for the prefetch "start here"
    calculation — over-fetching by a few days is cheap.
    """
    date_type = config.SPORTS[sport]['date_type']

    conn = _connect()
    try:
        if date_type == 'date':
            row = conn.execute(
                'SELECT MAX(date) FROM games WHERE sport = ? AND date IS NOT NULL',
                (sport,),
            ).fetchone()
            value = row[0] if row else None
            if not value:
                return None
            try:
                return datetime.date.fromisoformat(value)
            except ValueError:
                return None

        row = conn.execute(
            'SELECT MAX(week) FROM games WHERE sport = ? AND week IS NOT NULL',
            (sport,),
        ).fetchone()
        max_week = row[0] if row else None
        if max_week is None:
            return None
    finally:
        conn.close()

    # Find the most recent season that has Week1 defined and whose Week1 date
    # plus (max_week - 1) * 7 days is plausible.
    starts = getattr(config, '_WEEK1_STARTS', {}).get(sport, {})
    if not starts:
        return None
    today = datetime.date.today()
    best: Optional[datetime.date] = None
    for season_year, week1 in starts.items():
        candidate = week1 + datetime.timedelta(days=7 * (max_week - 1))
        if candidate <= today and (best is None or candidate > best):
            best = candidate
    return best


# ---------------------------------------------------------------------------
# Backtest history (per-sport per-season aggregates)
# ---------------------------------------------------------------------------

def _game_log_to_json(game_log) -> str:
    """Serialize a backtest game_log (list of GameResult dataclasses or dicts)."""
    out = []
    for g in game_log:
        if isinstance(g, dict):
            out.append(g)
            continue
        out.append({
            'game_index': g.game_index,
            'date_or_week': g.date_or_week,
            'pick': g.pick,
            'actual': g.actual,
            'correct': g.correct,
            'units': g.units,
            'kelly_units': g.kelly_units,
            'bet_line': g.bet_line,
            'unit_size': g.unit_size,
            'ev': g.ev,
            'away_lines': g.away_lines,
            'home_lines': g.home_lines,
        })
    return json.dumps(out)


def save_backtest_history(
    sport: str,
    season_year: int,
    model: str,
    *,
    start_date: str,
    end_date: str,
    total_games: int,
    games_picked: int,
    correct_picks: int,
    win_rate: Optional[float],
    flat_units: float,
    kelly_units: float,
    roi_flat: Optional[float],
    roi_kelly: Optional[float],
    max_drawdown: float = 0.0,
    game_log,
) -> None:
    """Upsert one aggregate row. `game_log` is a list of GameResult or dicts."""
    now = datetime.datetime.utcnow().isoformat(timespec='seconds')
    payload = (
        sport, season_year, model,
        start_date, end_date,
        int(total_games), int(games_picked), int(correct_picks),
        win_rate, float(flat_units), float(kelly_units),
        roi_flat, roi_kelly, float(max_drawdown),
        _game_log_to_json(game_log),
        now,
    )
    conn = _connect()
    try:
        with conn:
            conn.execute(
                'INSERT INTO backtest_history '
                '(sport, season_year, model, start_date, end_date, '
                ' total_games, games_picked, correct_picks, win_rate, '
                ' flat_units, kelly_units, roi_flat, roi_kelly, max_drawdown, '
                ' game_log_json, computed_at) '
                'VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) '
                'ON CONFLICT(sport, season_year, model) DO UPDATE SET '
                ' start_date    = excluded.start_date, '
                ' end_date      = excluded.end_date, '
                ' total_games   = excluded.total_games, '
                ' games_picked  = excluded.games_picked, '
                ' correct_picks = excluded.correct_picks, '
                ' win_rate      = excluded.win_rate, '
                ' flat_units    = excluded.flat_units, '
                ' kelly_units   = excluded.kelly_units, '
                ' roi_flat      = excluded.roi_flat, '
                ' roi_kelly     = excluded.roi_kelly, '
                ' max_drawdown  = excluded.max_drawdown, '
                ' game_log_json = excluded.game_log_json, '
                ' computed_at   = excluded.computed_at',
                payload,
            )
    finally:
        conn.close()


def load_backtest_history(
    sport: Optional[str] = None,
    model: str = 'logreg',
    *,
    include_game_log: bool = False,
) -> list[dict]:
    """
    Return aggregate rows ordered by (sport, season_year DESC).

    `include_game_log=False` (the default) skips the JSON blob to keep
    /api/history responses small. Pass True when consumers (e.g. recent_picks
    rebuilds, audits) actually need the per-game records.
    """
    cols = (
        'sport, season_year, model, start_date, end_date, '
        'total_games, games_picked, correct_picks, win_rate, '
        'flat_units, kelly_units, roi_flat, roi_kelly, max_drawdown, computed_at'
    )
    if include_game_log:
        cols = cols + ', game_log_json'

    conn = _connect()
    try:
        if sport is None:
            rows = conn.execute(
                f'SELECT {cols} FROM backtest_history '
                'WHERE model = ? ORDER BY sport, season_year DESC',
                (model,),
            ).fetchall()
        else:
            rows = conn.execute(
                f'SELECT {cols} FROM backtest_history '
                'WHERE sport = ? AND model = ? ORDER BY season_year DESC',
                (sport, model),
            ).fetchall()
    finally:
        conn.close()

    keys = [
        'sport', 'season_year', 'model', 'start_date', 'end_date',
        'total_games', 'games_picked', 'correct_picks', 'win_rate',
        'flat_units', 'kelly_units', 'roi_flat', 'roi_kelly',
        'max_drawdown', 'computed_at',
    ]
    if include_game_log:
        keys = keys + ['game_log_json']

    out = []
    for r in rows:
        row = dict(zip(keys, r))
        if include_game_log and row.get('game_log_json'):
            try:
                row['game_log'] = json.loads(row.pop('game_log_json'))
            except (TypeError, ValueError):
                row['game_log'] = []
        out.append(row)
    return out


# ---------------------------------------------------------------------------
# picks_log — production picks generated daily, settled when scores arrive
# ---------------------------------------------------------------------------

def _normalize_score(value) -> Optional[int]:
    """Coerce a stored score (str|int|None|NaN) to an int or None."""
    if value is None:
        return None
    if isinstance(value, float) and pd.isna(value):
        return None
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return None


def log_picks(
    sport: str,
    cache_key: str,
    game_date: str,
    picks,
    model: str = 'logreg',
) -> int:
    """
    Insert one picks_log row per pick. INSERT OR IGNORE on the UNIQUE constraint
    so re-running on the same (sport, cache_key, game_index, model) is a no-op.

    `picks` is a list of `picks.Pick` instances or dicts with the same fields.
    `game_date` should be a 'YYYY-MM-DD' string used for sorting/charting; for
    week-based sports infer it from the cached games' Date column or pass the
    day the prefetch ran on.

    Returns the count actually inserted.
    """
    if not picks:
        return 0

    now = datetime.datetime.utcnow().isoformat(timespec='seconds')
    rows = []
    for p in picks:
        get = (lambda k, default=None: p.get(k, default)) if isinstance(p, dict) else (lambda k, default=None: getattr(p, k, default))
        away_lines = get('away_lines') or []
        home_lines = get('home_lines') or []
        rows.append((
            sport, str(cache_key), game_date, int(get('game_index') or 0),
            get('away_team') or '', get('home_team') or '',
            get('away_abbr') or '', get('home_abbr') or '',
            get('pick') or 'No Pick',
            get('confidence'), get('away_prob'), get('home_prob'),
            json.dumps(list(away_lines)), json.dumps(list(home_lines)),
            get('bet_line'), get('ev'), get('unit_size') or 0.0,
            model, now,
        ))

    conn = _connect()
    inserted = 0
    try:
        with conn:
            for row in rows:
                cur = conn.execute(
                    'INSERT OR IGNORE INTO picks_log '
                    '(sport, cache_key, game_date, game_index, '
                    ' away_team, home_team, away_abbr, home_abbr, '
                    ' pick, confidence, away_prob, home_prob, '
                    ' away_lines_json, home_lines_json, '
                    ' bet_line, ev, unit_size, model, created_at) '
                    'VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
                    row,
                )
                inserted += cur.rowcount
    finally:
        conn.close()
    return inserted


def unsettled_picks(
    sport: Optional[str] = None,
    max_age_days: int = 30,
) -> list[dict]:
    """
    Return picks_log rows still awaiting score data. Older than `max_age_days`
    are dropped — if SBR never recorded a score by then, settling won't happen.
    """
    cutoff = (datetime.date.today() - datetime.timedelta(days=max_age_days)).isoformat()
    conn = _connect()
    try:
        if sport is None:
            rows = conn.execute(
                'SELECT id, sport, cache_key, game_date, game_index, '
                '       away_team, home_team, away_abbr, home_abbr, '
                '       pick, bet_line, unit_size, model '
                'FROM picks_log '
                'WHERE actual IS NULL AND game_date >= ? '
                'ORDER BY game_date DESC, id DESC',
                (cutoff,),
            ).fetchall()
        else:
            rows = conn.execute(
                'SELECT id, sport, cache_key, game_date, game_index, '
                '       away_team, home_team, away_abbr, home_abbr, '
                '       pick, bet_line, unit_size, model '
                'FROM picks_log '
                'WHERE actual IS NULL AND game_date >= ? AND sport = ? '
                'ORDER BY game_date DESC, id DESC',
                (cutoff, sport),
            ).fetchall()
    finally:
        conn.close()
    keys = [
        'id', 'sport', 'cache_key', 'game_date', 'game_index',
        'away_team', 'home_team', 'away_abbr', 'home_abbr',
        'pick', 'bet_line', 'unit_size', 'model',
    ]
    return [dict(zip(keys, r)) for r in rows]


def _result_from_scores(away_score, home_score) -> str:
    """'Away' | 'Home' | 'Tie' from numeric scores (or 'Tie' when unparseable)."""
    a = _normalize_score(away_score)
    h = _normalize_score(home_score)
    if a is None or h is None:
        return 'Tie'
    if a > h:
        return 'Away'
    if h > a:
        return 'Home'
    return 'Tie'


def settle_pick_record(pick_id: int, away_score, home_score) -> bool:
    """
    Settle one picks_log row. Returns True if the row was updated, False if
    the pick was missing or already settled.
    """
    from betmath import settle_pick

    conn = _connect()
    try:
        row = conn.execute(
            'SELECT pick, bet_line, unit_size, actual FROM picks_log WHERE id = ?',
            (int(pick_id),),
        ).fetchone()
        if row is None:
            return False
        pick_str, bet_line, unit_size, already_actual = row
        if already_actual is not None:
            return False

        actual = _result_from_scores(away_score, home_score)
        flat, kelly, result = settle_pick(
            pick_str, actual, bet_line, float(unit_size or 0.0),
        )
        now = datetime.datetime.utcnow().isoformat(timespec='seconds')

        a = _normalize_score(away_score)
        h = _normalize_score(home_score)

        with conn:
            conn.execute(
                'UPDATE picks_log SET '
                ' away_score = ?, home_score = ?, '
                ' actual = ?, result = ?, '
                ' flat_units = ?, kelly_units = ?, '
                ' settled_at = ? '
                'WHERE id = ?',
                (a, h, actual, result, flat, kelly, now, int(pick_id)),
            )
    finally:
        conn.close()
    return True


def recent_settled_picks(limit: int = 50) -> list[dict]:
    """Return the most-recently-settled picks across all sports, newest first."""
    conn = _connect()
    try:
        rows = conn.execute(
            'SELECT sport, game_date, away_team, home_team, away_abbr, home_abbr, '
            '       pick, bet_line, actual, result, flat_units, kelly_units, '
            '       unit_size, ev '
            'FROM picks_log '
            'WHERE actual IS NOT NULL '
            'ORDER BY game_date DESC, settled_at DESC '
            'LIMIT ?',
            (int(limit),),
        ).fetchall()
    finally:
        conn.close()
    keys = [
        'sport', 'game_date', 'away_team', 'home_team', 'away_abbr', 'home_abbr',
        'pick', 'bet_line', 'actual', 'result', 'flat_units', 'kelly_units',
        'unit_size', 'ev',
    ]
    return [dict(zip(keys, r)) for r in rows]


# ---------------------------------------------------------------------------
# Rolling backtest cache (last-N-days, computed on a daily cadence)
# ---------------------------------------------------------------------------

def save_rolling_backtest(
    sport: str,
    *,
    end_date: str,
    window_days: int,
    start_date: str,
    model: str,
    total_games: int,
    games_picked: int,
    correct_picks: int,
    win_rate: Optional[float],
    flat_units: float,
    kelly_units: float,
    max_drawdown: float,
    daily_units,
    game_log,
) -> None:
    """
    Upsert one row of the rolling cache. `daily_units` is a list of
    {day, units, kelly_units, cum_units, cum_kelly_units} dicts.
    """
    now = datetime.datetime.utcnow().isoformat(timespec='seconds')
    payload = (
        sport, end_date, int(window_days), start_date, model,
        int(total_games), int(games_picked), int(correct_picks),
        win_rate, float(flat_units), float(kelly_units), float(max_drawdown),
        json.dumps(list(daily_units)),
        _game_log_to_json(game_log),
        now,
    )
    conn = _connect()
    try:
        with conn:
            conn.execute(
                'INSERT INTO rolling_backtest_cache '
                '(sport, end_date, window_days, start_date, model, '
                ' total_games, games_picked, correct_picks, win_rate, '
                ' flat_units, kelly_units, max_drawdown, '
                ' daily_units_json, game_log_json, computed_at) '
                'VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) '
                'ON CONFLICT(sport, end_date, window_days, model) DO UPDATE SET '
                ' start_date       = excluded.start_date, '
                ' total_games      = excluded.total_games, '
                ' games_picked     = excluded.games_picked, '
                ' correct_picks    = excluded.correct_picks, '
                ' win_rate         = excluded.win_rate, '
                ' flat_units       = excluded.flat_units, '
                ' kelly_units      = excluded.kelly_units, '
                ' max_drawdown     = excluded.max_drawdown, '
                ' daily_units_json = excluded.daily_units_json, '
                ' game_log_json    = excluded.game_log_json, '
                ' computed_at      = excluded.computed_at',
                payload,
            )
    finally:
        conn.close()


def load_rolling_backtest(
    window_days: int,
    end_date: Optional[str] = None,
    model: str = 'logreg',
    *,
    include_game_log: bool = False,
) -> list[dict]:
    """
    Return rolling-cache rows for a given window. If `end_date` is None,
    returns rows whose end_date is the latest cached value per sport.
    """
    cols = (
        'sport, end_date, window_days, start_date, model, '
        'total_games, games_picked, correct_picks, win_rate, '
        'flat_units, kelly_units, max_drawdown, '
        'daily_units_json, computed_at'
    )
    if include_game_log:
        cols = cols + ', game_log_json'

    conn = _connect()
    try:
        if end_date is not None:
            rows = conn.execute(
                f'SELECT {cols} FROM rolling_backtest_cache '
                'WHERE window_days = ? AND model = ? AND end_date = ? '
                'ORDER BY sport',
                (int(window_days), model, end_date),
            ).fetchall()
        else:
            # Latest row per sport for this window
            rows = conn.execute(
                f'SELECT {cols} FROM rolling_backtest_cache AS r '
                'WHERE window_days = ? AND model = ? '
                '  AND end_date = (SELECT MAX(end_date) FROM rolling_backtest_cache '
                '                  WHERE sport = r.sport AND window_days = r.window_days '
                '                    AND model = r.model) '
                'ORDER BY sport',
                (int(window_days), model),
            ).fetchall()
    finally:
        conn.close()

    keys = [
        'sport', 'end_date', 'window_days', 'start_date', 'model',
        'total_games', 'games_picked', 'correct_picks', 'win_rate',
        'flat_units', 'kelly_units', 'max_drawdown',
        'daily_units_json', 'computed_at',
    ]
    if include_game_log:
        keys = keys + ['game_log_json']

    out = []
    for r in rows:
        row = dict(zip(keys, r))
        try:
            row['daily_units'] = json.loads(row.pop('daily_units_json') or '[]')
        except (TypeError, ValueError):
            row['daily_units'] = []
        if include_game_log and row.get('game_log_json'):
            try:
                row['game_log'] = json.loads(row.pop('game_log_json'))
            except (TypeError, ValueError):
                row['game_log'] = []
        out.append(row)
    return out


def rolling_computed_today(
    sport: str, window_days: int, model: str = 'logreg',
) -> bool:
    """
    True if the rolling row for (sport, window_days, model) was computed today.
    Uses UTC date to match the `computed_at` timestamp stored on save, so the
    check is consistent regardless of the host's local timezone.
    """
    today = datetime.datetime.utcnow().date().isoformat()
    conn = _connect()
    try:
        row = conn.execute(
            'SELECT computed_at FROM rolling_backtest_cache '
            'WHERE sport = ? AND window_days = ? AND model = ? '
            'ORDER BY end_date DESC LIMIT 1',
            (sport, int(window_days), model),
        ).fetchone()
    finally:
        conn.close()
    if row is None or not row[0]:
        return False
    return str(row[0]).startswith(today)


def daily_performance(days: int = 30) -> list[dict]:
    """
    Return one entry per day for the last `days` days with daily and cumulative
    flat + kelly units across all settled picks.

    Days with no settled picks still appear (units = 0) so a chart consumer can
    plot a continuous series without re-bucketing.
    """
    today = datetime.date.today()
    start = today - datetime.timedelta(days=max(int(days) - 1, 0))
    conn = _connect()
    try:
        rows = conn.execute(
            'SELECT game_date, '
            '       COALESCE(SUM(flat_units), 0) AS flat, '
            '       COALESCE(SUM(kelly_units), 0) AS kelly '
            'FROM picks_log '
            'WHERE actual IS NOT NULL AND game_date >= ? '
            'GROUP BY game_date',
            (start.isoformat(),),
        ).fetchall()
    finally:
        conn.close()
    by_day = {r[0]: (float(r[1]), float(r[2])) for r in rows}

    series = []
    cum_flat = 0.0
    cum_kelly = 0.0
    day = start
    while day <= today:
        flat, kelly = by_day.get(day.isoformat(), (0.0, 0.0))
        cum_flat += flat
        cum_kelly += kelly
        series.append({
            'day': day.isoformat(),
            'units': flat,
            'kelly_units': kelly,
            'cum_units': round(cum_flat, 4),
            'cum_kelly_units': round(cum_kelly, 6),
        })
        day += datetime.timedelta(days=1)
    return series
